package edu.ncsu.csc.CoffeeMaker.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.CoffeeMaker.models.Customer;
import edu.ncsu.csc.CoffeeMaker.models.User;

/**
 * Repository for interacting with Patient model. Method implementations
 * generated by Spring
 *
 * @author Kai Presler-Marshall
 * @param <T>
 *            Type of User
 *
 */
public interface CustomerRepository <T extends User> extends JpaRepository<Customer, String> {

}
