package edu.ncsu.csc.CoffeeMaker.repositories;

import edu.ncsu.csc.CoffeeMaker.models.InventoryManager;
import edu.ncsu.csc.CoffeeMaker.models.User;

/**
 * Repository for interacting with InventoryManager model. Method
 * implementations generated by Spring
 *
 * @author John Nguyen
 * @param <T>
 *            Type of user
 */
public interface InventoryManagerRepository <T extends User> extends UserRepository<InventoryManager> {

}
